#ifndef DUCHESS_CPP_FEATURETYPE_H
#define DUCHESS_CPP_FEATURETYPE_H

enum class FeatureType {
    MATERIAL,
    PARTNER_WIZARD,
    PAWN_DISTANCE,
    BIAS,
    CHECK,
    CHECKMATE,
    ATTACKING_DEFENDING,
    ATTACKING_DEFENDING_NAIVE,
    KING_DISTANCE,
    PIECE_SQUARE

};

#endif //DUCHESS_CPP_FEATURETYPE_H
